# Site settings
title: blog.lukmannulhakim.com
header-img: img/indo-home-bg.jpg
email: ahmad@lukmannulhakim.com
copyright_name: lukmannulhakim
description: "Just write and share"
baseurl: ""
url: "http://blog.lukmannulhakim.com/"
github_username:  lukmannulhakim
facebook_username:  ahmadlukmannulhakim
email_username:  ahmadlukmannulhakim@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
